# Dependencies
markdown:         redcarpet
highlighter:      rb-pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            The Young & Stupid Show
tagline:          'A boring blog'
description:      ""
url:              http://hyde.getpoole.com
baseurl:          /
plugins:
  - jekyll-paginate

author:
  name:           'Justin Meredith'
  url:            https://twitter.com/mdo

plugins: [jekyll-paginate]
paginate:         5
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
